### ISSUE TITLE
History API always shows the entire changeset, even for completely unrelated records

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#60] opened 2017-06-20 09:42 UTC
Currently, if you request the history of an object, you get the `ChangeSet` with all the changes, not just for the requested object.  This is confusing when the frontend presents this as "the changes made to this object".

The main issue here is multi-PUT.  You can change a whole bunch of related (or even non-related!) models, and it would be strange if those were excluded when asking for changes.  You could `with` them, but Binder doesn't necessarily know which related records belong to which requested record (and reconstructing the relations at that point in time would be quite computationally intensive)

**Comment by mmoreaux** [comment] 2017-06-20 14:02
This is by design. Sorta.

If you want just the changed instance, you can filter on `model` and `id` fields, leaving the relevant rows.

If you want related models as well, then... Which are those exactly? At the time of change? They might have been unrelated at that point, or were related but now aren't.

There are many questions like these, so the current history implementations assumes no answers to these and simply logs what changes per request. Everything else is TODO, and probably needs much discussion.

**Comment by mmoreaux** [comment] 2017-09-13 15:51
Discussed with @sjamaan, this is wontfix for now.

It may be worth revisiting in the future. In that case: we need clear use cases, and then an API proposal.

**Closed by mmoreaux** 2017-09-13 15:51 UTC
